version: '3.8'

services:
  # Traefik reverse proxy with HTTPS
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data:/data
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=your-email@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.com`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
    networks:
      - traefik

  # PostgreSQL database for Guacamole
  guacamole-db:
    image: postgres:15
    container_name: guacamole-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
    volumes:
      - guacamole-db-data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    networks:
      - guacamole

  # Guacamole daemon
  guacd:
    image: guacamole/guacd:1.5.3
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacamole

  # Guacamole web application
  guacamole:
    image: guacamole/guacamole:1.5.3
    container_name: guacamole
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
    depends_on:
      - guacamole-db
      - guacd
    labels:
      - traefik.enable=true
      - traefik.http.routers.guacamole.rule=Host(`guacamole.yourdomain.com`)
      - traefik.http.routers.guacamole.entrypoints=websecure
      - traefik.http.routers.guacamole.tls.certresolver=letsencrypt
      - traefik.http.services.guacamole.loadbalancer.server.port=8080
    networks:
      - traefik
      - guacamole

  # Ubuntu LXDE with TigerVNC
  ubuntu-lxde:
    image: backplane/lxde:latest
    container_name: ubuntu-lxde
    restart: unless-stopped
    environment:
      # VNC password (change this!)
      VNC_PASSWORD: changeme123
      # Display resolution
      RESOLUTION: 1920x1080
      # VNC display number
      DISPLAY: :1
    ports:
      - "5901:5901"  # VNC port
    volumes:
      - ubuntu-data:/home/ubuntu
    networks:
      - guacamole

networks:
  traefik:
    external: false
  guacamole:
    external: false

volumes:
  guacamole-db-data:
  ubuntu-data:
  traefik-data:
